### ISSUE TITLE
Error : Error while fetching cluster local : it seems to be unreachable

### ISSUE THREAD

**Issue by babbutycoon** [rackslab/Slurm-web#183] opened 2017-09-22 22:06 UTC
Hi I finally managed to install slurm-web on debian 8. But when I try to access the url i get this error.   

<img width="1266" alt="screen shot 2017-09-22 at 2 52 39 pm" src="https://user-images.githubusercontent.com/32208890/30765671-bf537a4e-9fa5-11e7-8d29-8c15921ba063.png">  

Below is my apache error.log   
```
[Fri Sep 22 14:48:33.347150 2017] [wsgi:error] [pid 7957:tid 140431155885824] [remote 10.10.223.247:32949] mod_wsgi (pid=7957): Target WSGI script '/usr/share/slurm-web/restapi/slurm-web-restapi.wsgi' cannot be loaded as Python module.
[Fri Sep 22 14:48:33.347235 2017] [wsgi:error] [pid 7957:tid 140431155885824] [remote 10.10.223.247:32949] mod_wsgi (pid=7957): Exception occurred processing WSGI script '/usr/share/slurm-web/restapi/slurm-web-restapi.wsgi'.
[Fri Sep 22 14:48:33.347285 2017] [wsgi:error] [pid 7957:tid 140431155885824] [remote 10.10.223.247:32949] Traceback (most recent call last):
[Fri Sep 22 14:48:33.347350 2017] [wsgi:error] [pid 7957:tid 140431155885824] [remote 10.10.223.247:32949]   File "/usr/share/slurm-web/restapi/slurm-web-restapi.wsgi", line 4, in <module>
[Fri Sep 22 14:48:33.347426 2017] [wsgi:error] [pid 7957:tid 140431155885824] [remote 10.10.223.247:32949]     from slurmrestapi import app as application
[Fri Sep 22 14:48:33.347451 2017] [wsgi:error] [pid 7957:tid 140431155885824] [remote 10.10.223.247:32949]   File "/usr/share/slurm-web/restapi/slurmrestapi.py", line 41, in <module>
[Fri Sep 22 14:48:33.347498 2017] [wsgi:error] [pid 7957:tid 140431155885824] [remote 10.10.223.247:32949]     from auth import (User, authentication_verify,
[Fri Sep 22 14:48:33.347528 2017] [wsgi:error] [pid 7957:tid 140431155885824] [remote 10.10.223.247:32949]   File "/usr/share/slurm-web/restapi/auth.py", line 144, in <module>
[Fri Sep 22 14:48:33.347562 2017] [wsgi:error] [pid 7957:tid 140431155885824] [remote 10.10.223.247:32949]     abort.mapping.update({403: CORSForbidden})
[Fri Sep 22 14:48:33.347613 2017] [wsgi:error] [pid 7957:tid 140431155885824] [remote 10.10.223.247:32949] AttributeError: 'function' object has no attribute 'mapping'
```

Below is my apache access.log   
```
10.10.223.247 - - [22/Sep/2017:14:54:54 -0700] "GET /slurm-web-conf/clusters.config.js HTTP/1.1" 304 263 "http://sjchpc/slurm/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36"
10.10.223.247 - - [22/Sep/2017:14:54:54 -0700] "GET /slurm/static/favicon.ico HTTP/1.1" 200 1450 "http://sjchpc/slurm/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36"
10.10.223.247 - - [22/Sep/2017:14:54:55 -0700] "GET /slurm-web-conf/config.json HTTP/1.1" 304 265 "http://sjchpc/slurm/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36"
10.10.223.247 - - [22/Sep/2017:14:54:55 -0700] "GET /slurm-web-conf/2d.colors.config.json HTTP/1.1" 304 264 "http://sjchpc/slurm/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36"
10.10.223.247 - - [22/Sep/2017:14:54:55 -0700] "GET /slurm-web-conf/2d.config.json HTTP/1.1" 304 263 "http://sjchpc/slurm/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36"
10.10.223.247 - - [22/Sep/2017:14:54:55 -0700] "GET /slurm-web-conf/topology.config.json HTTP/1.1" 304 265 "http://sjchpc/slurm/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36"
10.10.223.247 - - [22/Sep/2017:14:54:55 -0700] "GET /slurm-web-conf/3d.colors.config.json HTTP/1.1" 304 264 "http://sjchpc/slurm/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36"
10.10.223.247 - - [22/Sep/2017:14:54:55 -0700] "GET /slurm-restapi/cluster HTTP/1.1" 500 796 "http://hpc/slurm/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36"
```

Slurm is setup right and im able to run sinfo and other commands.

below are my configs   
```
Linux hpc 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux
```
permissions   under /etc/slurm-web/
```
-rw-r--r-- 1 root     root     3223 Sep 22 14:36 restapi.conf
drwxr-xr-x 2 root     root     4096 Sep 22 13:48 dashboard
-rw-r--r-- 1 root     root     1301 Sep 22 00:48 racks.xml
-r-------- 1 www-data www-data   64 Sep 21 23:19 secret.key
```
my restapi.conf   
```

# configure here all parameters for the Slurm-web REST API

[cors]
# give here the list of the domains from where the origin is authorized,
# separated by commas
#
# example : authorized_origins = http://example1.com,http://example2.com
authorized_origins = http://hpc

[config]
# Set to 'enable' to activate authentication.
# Authentication is based on LDAP, so an LDAP server and the good configuration
# for it, below in this file, are required.
authentication = enable
# Absolute path to the secret key file. This key is used to sign tokens
# on server-side and make sure they are not modified during network
# communications. The secret is required only if authentication is enabled.
# Make sure this file is readable by root and WCGI user only, and not
# world-readable.
secret_key = /etc/slurm-web/secret.key
# Set to 'enable' to activate cache.
#cache = enable
# Path for racks description (default to /etc/slurm-web/racks.xml).
racksxml = /etc/slurm-web/racks.xml

[roles]
# Allow guests users or not. Guests users have the 'all' role. Disabled by
# default.
# guests = disabled

# The `all` role if for all users that do not either have the user or admin
# role, including guests. This role can be:
#
# - disabled: users with the all role cannot access the REST API
# - enabled: users with the all role can access the REST API
#
# Enabled by default.
all = enabled

# The roles members can be defined with a list of groups (whose names
# are prefixed by @) and logins.
user = @chimistes,root
admin = @admin,bhargav

# Give here restricted fields about jobs for each role, separated by commas
restricted_fields_for_all = command
restricted_fields_for_user = command
restricted_fields_for_admin =

[acl]
# You can set here an access control list for each view of the dashboard for
# this cluster.
# This feature requires authentication to be enabled.
# For each view, you can give a list of groups (whose names are prefixed by @)
# and logins, to define who can access to this view.
# If no ACL is provided for a view, so every authenticated user can access to
# this view.
# i.e. ``jobs = @admin,pierre`` implies that the jobs view will be available
# only for every user from the group 'admin', and the user with 'pierre' as
# login.
# If you give an empty value for an entry (i.e. ``jobs =``), the corresponding
# view will not be accessible for anybody.
#
# Available views are : [
#   'jobs', 'jobsmap', 'partitions', 'reservations', 'qos', 'racks', '3dview',
#   'gantt', 'topology'
# ]

[ldap]
# Configure here settings to connect to your LDAP server.
uri = ldap://auth.dxcorr.local:389
base_people = ou=People,dc=internal,dc=local
base_group = ou=Group,dc=internal,,dc=local
# Optional path to CA certificate. Required only if ldaps protocol is used and
# CA certification not available in system certificates chain.
# cacert = /etc/ssl/certs/cacert.pem
expiration = 1296000

[cache]
# address for Redis server (default to host=localhost, port=6379)
redis_host = localhost
redis_port = 6379
# TTL for jobs (default to 10 seconds)
jobs_expiration = 10
# TTL for other informations (default to 60 seconds)
global_expiration = 86400

```

**Comment by babbutycoon** [comment] 2017-09-22 23:34
I dont seem to get the apache error anymore
```
/usr/share/slurm-web/restapi/slurm-web-restapi.wsgi' cannot be loaded as Python module.
```
I had to change "/etc/apache2/conf-available/slurm-web-restapi.conf" from
```
WSGIScriptAlias /slurm-restapi /usr/share/slurm-web/restapi/slurm-web-restapi.wsgi
```
to 
```
WSGIScriptAlias /slurm-restapi /usr/share/slurm-web/restapi/
```      

However I'm getting a new error as below
```
[client 10.10.223.249:58097] Target WSGI script not found or unable to stat: /usr/share/slurm-web/restapi/cluster
```

Any help is appreciated. Thanks

**Comment by babbutycoon** [comment] 2017-09-22 23:52
Iam now getting this error as well

```
Target WSGI script not found or unable to stat: /usr/share/slurm-web/conf-server/clusters.config.js
```

**Comment by nichoice** [comment] 2018-11-16 09:30
> I dont seem to get the apache error anymore
> 
> ```
> /usr/share/slurm-web/restapi/slurm-web-restapi.wsgi' cannot be loaded as Python module.
> ```
> I had to change "/etc/apache2/conf-available/slurm-web-restapi.conf" from
> 
> ```
> WSGIScriptAlias /slurm-restapi /usr/share/slurm-web/restapi/slurm-web-restapi.wsgi
> ```
> to
> 
> ```
> WSGIScriptAlias /slurm-restapi /usr/share/slurm-web/restapi/
> ```
> However I'm getting a new error as below
> 
> ```
> [client 10.10.223.249:58097] Target WSGI script not found or unable to stat: /usr/share/slurm-web/restapi/cluster
> ```
> Any help is appreciated. Thanks

Hi. Have you solved this problem?

**Comment by mehdid** [comment] 2019-02-12 09:44
I am not sure where the issue is but I can confirm that `WSGIScriptAlias /slurm-restapi` has to be set to `/usr/share/slurm-web/restapi/slurm-web-restapi.wsgi`.

**Comment by rezib** [comment] 2024-05-15 14:00
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 that is not impacted by this issue. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment] 2024-06-19 09:02
For the reasons explained in the previous comment, I finally close this issue.

**Closed by rezib** 2024-06-19 09:02 UTC
Labels: deprecated version, pending closure
